// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA8J4R5LfL_aLCBHaOObcj-QTFHKvidRQ',
    appId: '1:526408718699:web:2f859eba12ca3a5b19542e',
    messagingSenderId: '526408718699',
    projectId: 'chatapp-a92bc',
    authDomain: 'chatapp-a92bc.firebaseapp.com',
    storageBucket: 'chatapp-a92bc.firebasestorage.app',
    measurementId: 'G-Q6H0PEDVZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7iZxGgoDE-0Eh2noHH7KZADS4BrOHCTs',
    appId: '1:526408718699:android:ec521633f183e90619542e',
    messagingSenderId: '526408718699',
    projectId: 'chatapp-a92bc',
    storageBucket: 'chatapp-a92bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdJ5fH77bq1W40Izpp9BWgupp6x5krN7Q',
    appId: '1:526408718699:ios:4fdfe7abec1a792919542e',
    messagingSenderId: '526408718699',
    projectId: 'chatapp-a92bc',
    storageBucket: 'chatapp-a92bc.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdJ5fH77bq1W40Izpp9BWgupp6x5krN7Q',
    appId: '1:526408718699:ios:4fdfe7abec1a792919542e',
    messagingSenderId: '526408718699',
    projectId: 'chatapp-a92bc',
    storageBucket: 'chatapp-a92bc.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA8J4R5LfL_aLCBHaOObcj-QTFHKvidRQ',
    appId: '1:526408718699:web:491231eae26ed32c19542e',
    messagingSenderId: '526408718699',
    projectId: 'chatapp-a92bc',
    authDomain: 'chatapp-a92bc.firebaseapp.com',
    storageBucket: 'chatapp-a92bc.firebasestorage.app',
    measurementId: 'G-SZM5BV8YSG',
  );
}
